/*
 * This file is generated by MediaBoy at export time.
 * Do not edit manually — re-export from the Go tool to regenerate.
 *
 * For CGB (color) builds:  exported files include _palettes[] and _attr[]
 * For DMG (mono) builds:   only _tiles[] and _map[] are generated
 *
 * The actual main.c with correct symbol names is written to the output
 * directory alongside the .h/.c data files by ExportGBDK / ExportGBDKDMG.
 */

#include <gbdk/platform.h>
#include <stdint.h>

/* Placeholder — replace with the generated main.c from MediaBoy export */
void main(void) {
    while(1) { vsync(); }
}
